import { Recipe } from '../recipe';

export const RECIPES: Recipe[] = [
  { id: 1,
    title: 'White Chicken Chili',
    instructions: 'Crock-pot for 8 hours',
    ingredients: [
      {quantity: 3, name: 'Chicken', measurement: 'pounds'},
      {quantity: 1, name: 'Beans', measurement: '12 oz can'},
      {quantity: 2, name: 'Tomatoes', measurement: 'each'},
      {quantity: 1, name: 'Onion', measurement: 'each'},
      {quantity: 14, name: 'Cream', measurement: 'oz'},
      {quantity: 2, name: 'Shredded Cheese', measurement: 'cups'},
    ],
  },
  { id: 2,
    title: 'Turkey Meatballs',
    instructions: 'Cook in oven at 375 degrees for 4.5 - 5.0 hours',
    ingredients: [
      {quantity: 8, name: 'Ground Turkey', measurement: 'pounds'},
      {quantity: 5, name: 'BBQ Sauce', measurement: 'cups'},
      {quantity: 2, name: 'Onion Powder', measurement: 'Tbsp'},
      {quantity: 2, name: 'Eggs', measurement: 'each'},
    ],
  },
  { id: 3,
    title: 'Steak On The Grill',
    instructions: 'Grill over high heat for 3 minutes each side',
    ingredients: [
      {quantity: 10, name: 'Steak', measurement: 'pounds'},
      {quantity: 2, name: 'Salt', measurement: 'Tsp'},
      {quantity: 2, name: 'Pepper', measurement: 'Tsp'},
    ],
  },
  { id: 3,
    title: 'Korean Beef Bowls',
    instructions: 'Instant Pot for 3:00hrs, serve with white rice',
    ingredients: [
      {quantity: 4, name: 'Ground Beef', measurement: 'pounds'},
      {quantity: 2, name: 'Salt', measurement: 'Tsp'},
      {quantity: 2, name: 'Pepper', measurement: 'Tsp'},
      {quantity: 4, name: 'Hoisin Sauce', measurement: 'Tbsp'},
      {quantity: 3, name: 'Garlic', measurement: 'cloves'},
      {quantity: 2, name: 'Sesame Oil', measurement: 'Tsp'},
    ],
  },
  { id: 3,
    title: 'Tater Tot Hot Dish',
    instructions: 'Combine all ingredients in 9x13 baking pan, top with tater tots. Bake for 55mins at 375 degrees',
    ingredients: [
      {quantity: 6, name: 'Cream Of Chicken Soup', measurement: '13oz Cans'},
      {quantity: 4, name: 'Cream Of Mushroom Soup', measurement: '13oz Cans'},
      {quantity: 3, name: 'Ground Beef', measurement: 'pounds'},
      {quantity: 3, name: 'Frozen Corn', measurement: 'Cups'},
      {quantity: 1, name: 'Tater Tots', measurement: '18oz'},
      {quantity: 2, name: 'Salt', measurement: 'Tsp'},
      {quantity: 2, name: 'Tater Tots', measurement: 'Tsp'},
    ],
  },
  { id: 3,
    title: 'Chicken Tacos',
    instructions: 'Never stop eating them. Ever.',
    ingredients: [
      {quantity: 8, name: 'Chicken', measurement: 'pounds'},
      {quantity: 2, name: 'Beans', measurement: 'Tsp'},
      {quantity: 2, name: 'Salsa', measurement: 'Tsp'},
      {quantity: 2, name: 'Cheese', measurement: 'Tsp'},
      {quantity: 2, name: 'Lettuce', measurement: 'Tsp'},
      {quantity: 2, name: 'Hot Sauce', measurement: 'Tsp'},
    ],
  },
];


